### PR TITLE
Added jumpBetweenOpeningAndClosingSymbols command

### PR DESCRIPTION
**Pull request by Kotsuha**
I use VSCode's default shortcut `ctrl+shift+\`  to jump between opening and closing brackets. I work with C# so I want to jump between `#if` `#endif` `#region` `#endregion` as well. As far as I know VSCode doesn't support it.

This extension supports custom symbols and provides shortcuts to jump to opening and closing brackets, but it doesn't have a shortcut to jump between them like the default `ctrl+shift+\` do. I tried to add this feature in this commit.

bracket-highlighter

Currently the highlighted part seems not correct, as you can see in the GIF. It seems to be an old bug.

Also I am not sure about the change I made in `src/extension.ts`.
```
		if (startSymbol.symbol === '') {
			return;
		}
```

Feel free to use this PR or not. Thank you for this extension :) I've been using it for a long time.

### CODE REVIEW

**Comment by Durzn** [comment]
Thanks for using the extension and even improving it :) Your changes look fine at first glance, I'll take a deeper look later on.
Could you try to provide a minimal example where the highlighted part is not correct? I'd love to get rid of it.
The interesting part would be the custom symbols you configured and a minimal example in a text file where the error occurs.

**Comment by Kotsuha** [comment]
Minimal example:

```
#region Test
public void BeginDrag(EdgeOrCorner edgeOrCorner, Vector2 pos)
{
    Debug.Log("Dummy");
}
#endregion
```

Settings:

```
{
    "BracketHighlighter.customSymbols": [
        {
            "open": "#region",
            "close": "#endregion"
        }
    ]
}
```

**Comment by Durzn** [comment]
Thanks, I fixed it in the following pull request which I will merge soon-ish. https://github.com/Durzn/BracketHighlighter/pull/27
I'll take a look at your changes in the coming days, thank you very much for contributing :)

**Comment by Durzn** [comment]
I tried it out and fixed some small stuff, could you test that everything still works for you? If you say everything is fine, I'll merge and publish this.

**Comment by Kotsuha** [comment]
Thank you. I'll get back to you these few days.

**Comment by Kotsuha** [comment]
> I tried it out and fixed some small stuff, could you test that everything still works for you?

I see that you uploaded the extension to v2.3.2. Do I test it by using v2.3.2 or do I test it by downloading this repository?

**Comment by Durzn** [comment]
Oh sorry, 2.3.2 just includes the backwards search fix. You‘d need to package this branch and use this version. If that‘s too much overhead it‘s no problem, I can also just release it next week.

**Comment by Kotsuha** [comment]
I haven't done this before but I kind of want to try it. However, I don't know which commit I should package. From my understanding, I should test a version that contains both my changes and your changes, right? Do I click the "Update branch" to merge your changes?

If it is not easy to explain that's okay. I can wait for your release :)

BracketHighlighterTestQuestion

**Comment by Durzn** [comment]
I honestly have not much experience with github pull requests, but based on your screenshot I‘d assume that you could merge the main branch back into yours that way and then you‘d have both fixes. 
To build the extension you‘d need to setup a vscode environment (https://code.visualstudio.com/api/get-started/your-first-extension) and run „vsce package“, then you can manually install the new extension version with the generated vsix file.
I‘d package it for you and attach it, but I won‘t have access to my pc for a few days.

**Comment by Kotsuha** [comment]
I've built the vsix and tested it. Seems like there are issues. Haven't looked into it.
rec

```
public class Foo
{
#if UNITY_EDITOR
    
        public static bool Bar;
    
#endif

}

```

```
{
    "BracketHighlighter.customSymbols": [
        {
            "open": "#if",
            "close": "#endif"
        }
    ]
}
```

**Comment by Durzn** [comment]
Thanks, it should be fixed now. Could you double check?

**Comment by Kotsuha** [comment]
> Thanks, it should be fixed now. Could you double check?

It's fixed. Thank you.
I want to modify it a little. Will get back to you later.

**Comment by Kotsuha** [comment]
Does this extension want to support multiple cursors? If so, I noticed this behavior has changed:

5563f8c2
5563f8c2

63602868


```
class Foo
{
    void Bar()
    {
        var arr = new int[0];
    }
}
```

**Comment by Durzn** [comment]
Yes, multiple cursors should be supported, I‘ll take a look

**Comment by Kotsuha** [comment]
Sorry I am a little busy this weekend. I'll let you know when I finish the `jumpBetweenOpeningAndClosingSymbols` command (I want to make it support multi-cursors as well). Hopefully tomorrow, or else it'll be next weekend.

**Comment by Kotsuha** [comment]
The `jumpBetweenOpeningAndClosingSymbols` is done. Feel free to modify anything.

What I've added:
1. Make `jumpBetweenOpeningAndClosingSymbols` support multiple cursors.
2. Add options to specify the strategy to be used when performing `jumpBetweenOpeningAndClosingSymbols`. There are two strategies: 
    - toSymbolStart - Always jump to the start of a symbol. This is the same as VS Code's default <kbd>Ctrl+Shift+\\</kbd> behavior.
    - toSymbolOppositeSide - Jump to the "opposite" side of a symbol.

bracket-highlighter-fork-demo3-strategy-default


If you want to override the strategy to be used for a specific symbol pair, you can edit the settings.json, for example:

```
{
    "BracketHighlighter.customSymbols": [
        {
            "open": "#if",
            "close": "#endif",
            "preferredJumpBetweenStrategy": "toSymbolStart"
        },
        {
            "open": "#region",
            "close": "#endregion",
            "preferredJumpBetweenStrategy": "toSymbolStart"
        },
    ],
    "BracketHighlighter.defaultJumpBetweenStrategy": "toSymbolOppositeSide",
}
```

**Comment by Durzn** [comment]
Thanks, I'll take a look! Could you just clarify what the difference between "toSymbolStart" and the "jumpToOpeningSymbol" command is? Is that just so you can override the hotkey action?

**Comment by Kotsuha** [comment]
> Could you just clarify what the difference between "toSymbolStart" and the "jumpToOpeningSymbol" command is?

The "toSymbolStart" is a strategy for the "jumpBetweenOpeningAndClosingSymbols" command. The "jumpBetweenOpeningAndClosingSymbols" command jumps between opening and closing symbols, but should it jump to the inside or outside of the symbol? It depends on the strategy. Currently there are two strategies, "toSymbolStart" and "toSymbolOppositeSide".

---

Command "jumpToOpeningSymbol"
```
|{    }  -->  {|   }
 {|   }  -->  {|   }
 {   |}  -->  {|   }
 {    }| -->  {|   }
```
Command "jumpBetweenOpeningAndClosingSymbols" using "toSymbolStart" strategy (This behavior is the same as VS Code's default shortcut <kbd>ctrl+shift+\\</kbd>)
```
|{    }  -->  {   |}
 {|   }  -->  {   |}
 {   |}  --> |{    }
 {    }| --> |{    }
```
Command "jumpBetweenOpeningAndClosingSymbols" using "toSymbolOppositeSide" strategy
```
|{    }  -->  {    }|
 {|   }  -->  {   |}
 {   |}  -->  {|   }
 {    }| --> |{    }
```

**Comment by Durzn** [comment]
Sorry for the delayed response, I think your solution is fine. Did you forget to push the latest changes? I see no commit for the latest comment you posted. Other than that I'm fine if we merge it like that

**Comment by Kotsuha** [comment]
Oops, sorry I forgot to merge the changes into main branch. It should be there now.

**Comment by Durzn** [comment]
Thanks, I just had a tiny commit, because it overwrote the cursor selections when an empty list was passed to setSelectionPositions. It didn't affect anything on my machine but it just feels better not to actively overwrite the selections to nothing.
Thanks for the idea and implementation, it was very interesting to read your code.
Is it okay if I mention you in the changelog?

**Comment by Kotsuha** [comment]
Sure, it's okay to mention me in the changelog. This is also an interesting experience for me. It's my first time creating such a large-scale pull request, and it's literally only the second time I've ever created a pull request.

**Pull request merged**
